### PR TITLE
Implementing BFS and DFs. Fixes #1

### LINKED ISSUE #1: Add new Data Structure algorithms (C++ only)
Contribute any new **Data Structure** algorithm to the repo to get the Limited Edition Hacktoberfest t-shirt. 

Instructions for contributing:
1. Fork this repo
2. Clone the forked repo to your local system
3. Add new files to the cloned folder
4. Commit the changes
5. Send a pull request

**Please restrain from contributing the same data structures already present in the repository.**

### PR DESCRIPTION
**Pull request by ronika-das**
I have created a program to rotate an array data structure

### CODE REVIEW

**Comment by sbis04** [comment]
Please add Data Structure algorithms based on **Graph** and **Hash Tables**.

**Comment by ronika-das** [comment]
oh okay. will do the necessary

**Comment by ronika-das** [comment]
i have added DFS and BFS algos for graphs, let me know if this works :)

**Comment by sbis04** [comment]
Thank you for your contribution! 🎉

**Pull request merged**
